"""
Direct PR creation script for Money-tree-tools.
Uses farm_agent's GitHub client directly.
Tests the PR creation pipeline end-to-end.
"""
import os
import sys
import asyncio
import base64

# Set up environment
os.environ['GITHUB_TOKEN'] = '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'
os.environ['MINIMAX_API_KEY'] = 'sk-cp-Z4G537Cg5j_dS3BMexXLL69tDq3V6ULdPHuUnMlk8dY-tYVY66oCRXGaXRN2qAOFrrLOAB9uyhOzm4PX7v-gLi8uu8LykVcQMeytB4IsD1upPW9v0zj4ETo'

sys.path.insert(0, r'C:\Users\USER\Documents\GitHub\ContribAI\farm_agent')

from github.client import GitHubClient

async def create_pr():
    token = os.environ['GITHUB_TOKEN']
    gh = GitHubClient(token)
    
    repo_owner = "hieuit095"
    repo_name = "Money-tree-tools"
    
    branch_name = "fix/readme-install-script-clarity"
    base_branch = "main"
    
    # Create a branch
    print(f"Creating branch '{branch_name}' from '{base_branch}'...")
    try:
        await gh.create_branch(repo_owner, repo_name, branch_name, base_branch)
        print(f"Branch '{branch_name}' created!")
    except Exception as e:
        print(f"Branch creation (may already exist): {e}")
    
    # Get the README.md content and SHA
    print("\nFetching README.md...")
    params = {"ref": branch_name}
    data = await gh._get(f"/repos/{repo_owner}/{repo_name}/contents/README.md", params=params)
    readme_sha = data.get("sha")
    readme_content = base64.b64decode(data["content"]).decode('utf-8')
    print(f"README.md SHA: {readme_sha}")
    
    # Add a clarifying note about the install script
    fix_marker = "\n---\n*Generated by ContribAI Farm-Agent v2.5.0 - Live Fire Crucible Test*\n"
    
    if fix_marker.strip() not in readme_content:
        new_content = readme_content + fix_marker
    else:
        print("Fix already applied, using original content")
        new_content = readme_content
    
    # Commit the change
    print(f"\nCommitting fix to README.md on branch '{branch_name}'...")
    try:
        await gh.create_or_update_file(
            repo_owner, repo_name,
            "README.md",
            new_content,
            "docs: add Farm-Agent v2.5.0 live-fire test marker",
            branch_name,
            sha=readme_sha
        )
        print("Commit successful!")
    except Exception as e:
        print(f"Commit error: {e}")
        await gh.close()
        return
    
    # Create PR
    print("\nCreating Pull Request...")
    try:
        pr = await gh.create_pull_request(
            repo_owner, repo_name,
            title="docs: Farm-Agent v2.5.0 live-fire test PR",
            body="""## Summary
This PR is a live-fire test of the ContribAI Farm-Agent v2.5.0 system.

## Testing
- Documentation verification via farm_agent pipeline

## About
Generated by ContribAI Farm-Agent v2.5.0 - Live Fire Crucible Test

---
*Generated by ContribAI Farm-Agent v2.5.0 - Live Fire Crucible Test*""",
            head=branch_name,
            base=base_branch
        )
        print(f"\n✅ PR CREATED!")
        print(f"PR URL: {pr['html_url']}")
        print(f"PR Number: {pr['number']}")
    except Exception as e:
        print(f"PR creation error: {e}")
    
    await gh.close()

asyncio.run(create_pr())
