"""
Direct PR creation script for zero-code.
Uses farm_agent's GitHub client directly.
"""
import os
import sys
import asyncio
import base64

os.environ['GITHUB_TOKEN'] = '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'
os.environ['MINIMAX_API_KEY'] = 'sk-cp-Z4G537Cg5j_dS3BMexXLL69tDq3V6ULdPHuUnMlk8dY-tYVY66oCRXGaXRN2qAOFrrLOAB9uyhOzm4PX7v-gLi8uu8LykVcQMeytB4IsD1upPW9v0zj4ETo'

sys.path.insert(0, r'C:\Users\USER\Documents\GitHub\ContribAI\farm_agent')
from github.client import GitHubClient

async def create_pr():
    gh = GitHubClient(os.environ['GITHUB_TOKEN'])
    
    repo_owner = "hieuit095"
    repo_name = "zero-code"
    branch_name = "docs/farm-agent-live-fire-test"
    base_branch = "main"
    
    # Create branch
    print(f"Creating branch '{branch_name}'...")
    try:
        await gh.create_branch(repo_owner, repo_name, branch_name, base_branch)
        print(f"Branch created!")
    except Exception as e:
        print(f"Branch creation: {e}")
    
    # Get README.md
    print("Fetching README.md...")
    params = {"ref": branch_name}
    data = await gh._get(f"/repos/{repo_owner}/{repo_name}/contents/README.md", params=params)
    readme_sha = data["sha"]
    readme_content = base64.b64decode(data["content"]).decode('utf-8')
    
    # Add footer
    fix_marker = "\n---\n*Generated by ContribAI Farm-Agent v2.5.0 - Live Fire Crucible Test*\n"
    if fix_marker.strip() not in readme_content:
        new_content = readme_content + fix_marker
    else:
        print("Fix already applied")
        new_content = readme_content
    
    # Commit
    print("Committing fix...")
    await gh.create_or_update_file(
        repo_owner, repo_name,
        "README.md", new_content,
        "docs: add Farm-Agent live-fire test marker",
        branch_name, sha=readme_sha
    )
    print("Committed!")
    
    # Create PR
    print("Creating Pull Request...")
    try:
        pr = await gh.create_pull_request(
            repo_owner, repo_name,
            title="docs: Farm-Agent v2.5.0 live-fire test PR",
            body="""## Summary
Live-fire test of the ContribAI Farm-Agent v2.5.0 system.

## Testing
- Documentation verification via farm_agent pipeline

---
*Generated by ContribAI Farm-Agent v2.5.0 - Live Fire Crucible Test*""",
            head=branch_name,
            base=base_branch
        )
        print(f"PR CREATED: {pr['html_url']}")
    except Exception as e:
        print(f"PR creation: {e}")
    
    await gh.close()

asyncio.run(create_pr())
