"""LLM-powered contribution generator.

Takes findings from the analysis engine and generates
actual code changes, tests, and commit messages that
follow the target repository's coding conventions.
"""

from __future__ import annotations

import difflib
import json
import logging
import re
from datetime import UTC, datetime

# ── Module-level Gag Order regex — used by both _generate and fix_contribution_from_error ──
_GHOST_DISCLOSURE_RE = re.compile(
    r"(?i)(as an ai|ai generated|language model|openai|minimax|"
    r"automated bot|generated by ai|ai assistant|contribai|farm_agent|"
    r"generated by this|this pr was generated|i was developed by)",
    re.IGNORECASE,
)

# Strip (not abort) — used for untrusted RAG-retrieved content
_STRIP_AI_RE = re.compile(
    r"(?i)(as an ai|ai generated|language model|openai|minimax|"
    r"automated bot|generated by ai|ai assistant|contribai|farm_agent|"
    r"generated by this|this pr was generated|i was developed by)",
    re.IGNORECASE,
)


# ── XSS escape function — strips dangerous HTML/JavaScript patterns ─────────────────
_XSS_SCRIPT_RE = re.compile(r"<script[^>]*>.*?</script>", re.IGNORECASE | re.DOTALL)
_XSS_EVENT_HANDLER_RE = re.compile(r"\bon\w+\s*=", re.IGNORECASE)
_XSS_JAVASCRIPT_RE = re.compile(r"javascript\s*:", re.IGNORECASE)


def escape_html_xss(text: str) -> str:
    """Strip dangerous XSS patterns from untrusted text.

    Removes:
    - <script> tags and their contents
    - on* event handler attributes (onclick=, onerror=, onload=, etc.)
    - javascript: URI schemes

    Used to sanitize any user-controlled text that may appear in
    GitHub issue/PR bodies to prevent XSS attacks on GitHub's UI.

    Args:
        text: Raw text that may contain XSS payloads.

    Returns:
        Text with XSS patterns replaced by placeholder strings.
    """
    if not text:
        return text
    text = _XSS_SCRIPT_RE.sub("[XSS-STRIPPED]", text)
    text = _XSS_EVENT_HANDLER_RE.sub("xss-blocked=", text)
    text = _XSS_JAVASCRIPT_RE.sub("xss-blocked:", text)
    return text


def _sanitize_text(text: str, field_name: str) -> str:
    """Sanitize free-form LLM text against AI disclosures (Gag Order).

    Used for PR titles, commit messages, and issue bodies — any field
    where the LLM produces free text that could leak the AI identity.

    Args:
        text: The raw LLM-generated text.
        field_name: Human-readable name of the field (for error messages).

    Returns:
        The sanitized text.

    Raises:
        GenerationError: If an AI disclosure is detected.
    """
    if not text:
        return text
    if _GHOST_DISCLOSURE_RE.search(text):
        logger.warning("Gag Order: AI disclosure detected in %s. Aborting.", field_name)
        raise GenerationError(
            f"LLM output in '{field_name}' contains forbidden AI disclosure: "
            f"{_GHOST_DISCLOSURE_RE.findall(text)}"
        )
    return text

from farm_agent.analysis.mapper import RepoMapper
from farm_agent.core.config import ContributionConfig
from farm_agent.core.exceptions import ContextMissingError, GenerationError
from farm_agent.core.models import (
    Contribution,
    ContributionType,
    FileChange,
    Finding,
    RepoContext,
)
from farm_agent.llm.context import build_generator_system_prompt
from farm_agent.llm.provider import LLMProvider
from farm_agent.tools.protocol import READ_FILE_TOOL_SCHEMA, GitHubTool
from farm_agent.core.rag import RepoIndexer
from farm_agent.generator.reviewer import ReviewerAgent

logger = logging.getLogger(__name__)

# Maximum tool calls per generation session to prevent infinite loops
MAX_TOOL_CALLS = 3


class ContributionGenerator:
    """Generate code contributions from analysis findings."""

    def __init__(self, llm: LLMProvider, config: ContributionConfig, *, memory=None, pipeline_config=None):
        self._llm = llm
        self._config = config
        self._memory = memory  # Optional Memory for repo_preferences
        # Configurable patch retry limit (from PipelineConfig or default)
        self._max_patch_retries = getattr(pipeline_config, "max_patch_retries", 2) if pipeline_config else 2
        # Adversarial Reviewer — completely independent entity with its own LLM
        self._reviewer = ReviewerAgent(llm, max_review_tokens=800)

    async def generate(
        self,
        finding: Finding,
        context: RepoContext,
        *,
        guidelines=None,
        github_client=None,
    ) -> Contribution | None:
        """Generate a contribution for a single finding.

        Steps:
        1. Build context-aware prompt
        2. Get LLM to generate the fix
        3. Parse structured output into FileChanges
        4. Generate commit message
        5. Self-review the generated code
        """
        import asyncio
        try:
            # 0: Fetch repo style from merged PRs (optional)
            async def _fetch_style() -> str:
                if github_client is None:
                    return ""
                try:
                    prs_data = await github_client.get_recent_merged_prs(
                        context.repo.owner, context.repo.name,
                    )
                    from farm_agent.llm.context import extract_style_guide
                    return extract_style_guide(prs_data)
                except Exception as exc:
                    logger.debug("Style mimicry skipped: %s", exc)
                    return ""

            # 0.5: Generate project skeleton map for architectural awareness
            async def _fetch_map() -> str:
                if github_client is None:
                    return ""
                try:
                    mapper = RepoMapper()
                    async def _fetch(path: str) -> str:
                        content = await github_client.get_file_content(
                            context.repo.owner, context.repo.name, path,
                        )
                        context.relevant_files[path] = content
                        return content
                    return await mapper.generate_map(context.file_tree, _fetch)
                except Exception as exc:
                    logger.debug("Project map generation skipped: %s", exc)
                    return ""

            # Concurrent fetching to overclock system pipeline
            style_task = asyncio.create_task(_fetch_style())
            map_task = asyncio.create_task(_fetch_map())
            prefs_task = asyncio.create_task(self._get_repo_preferences(context))

            style_guide, project_map, repo_prefs = await asyncio.gather(
                style_task, map_task, prefs_task
            )

            # ── P0-1 GRACEFUL CONTEXT FALLBACK — 3-tier rescue before aborting ─────────
            # The generator MUST have the actual source file content. Without it,
            # the LLM would hallucinate edits against an empty context.
            # TIER 1: Already-fetched file content (RAG/ChromaDB success)
            target_file_content = context.relevant_files.get(finding.file_path)

            # TIER 2: Explicit GitHubClient fetch (RAG was empty but we can still get the file)
            if not target_file_content and github_client is not None and finding.file_path:
                logger.warning(
                    "RAG miss for '%s' — attempting direct GitHub fetch for '%s'.",
                    finding.title,
                    finding.file_path,
                )
                try:
                    direct_content = await github_client.get_file_content(
                        context.repo.owner,
                        context.repo.name,
                        finding.file_path,
                    )
                    if direct_content:
                        context.relevant_files[finding.file_path] = direct_content
                        target_file_content = direct_content
                        logger.info(
                            "Tier-2 GitHub fetch succeeded for '%s' — context recovered.",
                            finding.file_path,
                        )
                except Exception as gh_exc:
                    logger.debug(
                        "Tier-2 GitHub fetch failed for '%s': %s",
                        finding.file_path,
                        gh_exc,
                    )

            # TIER 3: Deduce file from project_map (last resort before aborting)
            if not target_file_content and project_map and finding.file_path:
                logger.warning(
                    "RAG miss and GitHub fetch failed for '%s' — "
                    "scanning project_map for clues about '%s'.",
                    finding.title,
                    finding.file_path,
                )
                # The project_map is a structural overview — scan it for the target file
                # to confirm the file exists in the repo even if we cannot fetch it
                map_lower = project_map.lower()
                target_lower = finding.file_path.lower()
                if target_lower in map_lower or any(
                    segment in map_lower for segment in [finding.file_path]
                ):
                    # The file IS in the repo (confirmed by map), but we still cannot
                    # fetch it — try one more explicit fetch with a fallback path
                    if github_client is not None:
                        for path_variant in [
                            finding.file_path,
                            finding.file_path.lstrip("/"),
                            finding.file_path.replace("//", "/"),
                        ]:
                            try:
                                fallback_content = await github_client.get_file_content(
                                    context.repo.owner,
                                    context.repo.name,
                                    path_variant,
                                )
                                if fallback_content:
                                    context.relevant_files[finding.file_path] = fallback_content
                                    target_file_content = fallback_content
                                    logger.info(
                                        "Tier-3 map-assisted fetch succeeded for '%s'.",
                                        finding.file_path,
                                    )
                                    break
                            except Exception:
                                continue

            # ABORT only if ALL 3 tiers failed
            if not target_file_content:
                logger.error(
                    "ContextMissingError: no file content for '%s' (path='%s') — "
                    "RAG returned empty, GitHub fetch failed, and project_map "
                    "could not locate the file. "
                    "ABORTING generation to prevent blind code hallucination.",
                    finding.title,
                    finding.file_path,
                )
                raise ContextMissingError(
                    f"No usable context for target file: {finding.file_path}. "
                    f"Tier-1 (RAG): miss, Tier-2 (GitHub fetch): failed, "
                    f"Tier-3 (project_map): could not confirm file location. "
                    f"Generation is BLOCKED."
                )
            # ─────────────────────────────────────────────────────────────────────────────

            # 1 & 2: Generate the fix via agentic loop
            prompt = self._build_generation_prompt(finding, context, repo_prefs=repo_prefs)
            system = self._build_system_prompt(
                context, style_guide=style_guide, project_map=project_map,
            )

            response = await self._agentic_generate(
                prompt,
                system=system,
                github_client=github_client,
                context=context,
            )

            # 3: Parse output → apply search/replace to original content
            # Patch-Correction Retry Loop: if the patcher fails to apply
            # any edits (LLM hallucinated the SEARCH block), re-prompt the
            # LLM with the file content and ask for a corrected patch.
            MAX_PATCH_RETRIES = self._max_patch_retries
            changes = self._parse_changes(response, context)
            patch_attempt = 0
            while not changes and patch_attempt < MAX_PATCH_RETRIES:
                patch_attempt += 1
                logger.warning(
                    "Patch attempt %d/%d failed for %s — re-prompting LLM",
                    patch_attempt, MAX_PATCH_RETRIES, finding.title,
                )
                # Build a correction prompt with the actual file content
                file_content = context.relevant_files.get(finding.file_path, "")
                retry_prompt = (
                    "Your previous SEARCH block was NOT FOUND in the file. "
                    "This usually happens because of hallucinated lines, "
                    "incorrect indentation, or using `...` to skip lines.\n\n"
                    "Here is the ACTUAL file content you must match against:\n"
                    f"```\n{file_content[:6000]}\n```\n\n"
                    "Please review and provide the EXACT, VERBATIM block of code "
                    "you want to replace. Copy it character-for-character from the "
                    "file above. Do not use `...` to skip lines. Do not modify "
                    "indentation or whitespace.\n\n"
                    + prompt  # Re-include the original task prompt
                )
                response = await self._agentic_generate(
                    retry_prompt,
                    system=system,
                    github_client=github_client,
                    context=context,
                )
                changes = self._parse_changes(response, context)

            if not changes:
                logger.warning("No valid changes parsed for finding: %s", finding.title)
                return None

            # ── Sanity Check: Abort if patch is a no-op ──────────────────────
            for change in changes:
                if change.is_new_file:
                    continue  # new files are OK
                # Check if the change only touches comments/whitespace (replace === search)
                if hasattr(change, "edits") and change.edits:
                    for edit in change.edits:
                        search = getattr(edit, "search", "") or ""
                        replace = getattr(edit, "replace", "") or ""
                        # Both empty → no-op; Both identical → no functional change
                        if search == replace:
                            logger.warning(
                                "🗑️ Sanity check FAILED for '%s' — patch is a no-op "
                                "(search == replace). Aborting PR.",
                                finding.title,
                            )
                            return None
            # ──────────────────────────────────────────────────────────────────

            # 4: Generate commit message
            commit_msg = await self._generate_commit_message(finding, changes, context)

            # 5: Generate branch name
            branch_name = self._generate_branch_name(finding)

            # Build the contribution
            contribution = Contribution(
                finding=finding,
                contribution_type=finding.type,
                title=self._generate_pr_title(finding, guidelines=guidelines),
                description=finding.description,
                changes=changes,
                commit_message=commit_msg,
                branch_name=branch_name,
                generated_at=datetime.now(UTC),
            )

            # 6: Adversarial review loop — paranoid Senior Security Auditor
            # If the reviewer REJECTs, the Generator rewrites with the critique.
            # This is a completely SEPARATE entity from the Generator — no shared history.
            review_attempt = 0
            max_review_retries = self._config.max_review_retries
            latest_contribution = contribution
            latest_changes = changes

            while review_attempt <= max_review_retries:
                verdict = await self._reviewer.review(latest_contribution, context)
                if verdict["decision"] == "APPROVE":
                    logger.info(
                        "Adversarial review PASSED for: %s (attempt %d)",
                        finding.title,
                        review_attempt + 1,
                    )
                    break

                critique = verdict["critique"]
                logger.warning(
                    "🔴 Adversarial review REJECTED for: %s — attempt %d/%d",
                    finding.title,
                    review_attempt + 1,
                    max_review_retries + 1,
                )
                if critique:
                    logger.info("Critique: %s", critique[:300])

                if review_attempt >= max_review_retries:
                    # All retries exhausted — discard this finding to protect the repo
                    logger.error(
                        "🛑 Adversarial Review Failed for '%s' — discarding finding after %d attempts. "
                        "The patch was not good enough to pass our security audit.",
                        finding.title,
                        max_review_retries + 1,
                    )
                    return None

                # Rewrite with critique appended to the prompt
                review_attempt += 1
                logger.info("Rewriting patch with critique (attempt %d)...", review_attempt)

                # Build rewrite prompt: append critique to original generation prompt
                rewrite_prompt = self._build_generation_prompt(
                    finding, context,
                    repo_prefs=repo_prefs,
                    adversarial_critique=critique,
                )
                response = await self._agentic_generate(
                    rewrite_prompt,
                    system=system,
                    github_client=github_client,
                    context=context,
                )
                latest_changes = self._parse_changes(response, context)
                if not latest_changes:
                    logger.warning("Rewrite attempt produced no valid changes for: %s", finding.title)
                    return None

                # Regenerate commit message and branch name for the rewritten patch
                new_commit_msg = await self._generate_commit_message(finding, latest_changes, context)
                new_branch_name = self._generate_branch_name(finding)

                latest_contribution = Contribution(
                    finding=finding,
                    contribution_type=finding.type,
                    title=self._generate_pr_title(finding, guidelines=guidelines),
                    description=finding.description,
                    changes=latest_changes,
                    commit_message=new_commit_msg,
                    branch_name=new_branch_name,
                    generated_at=datetime.now(UTC),
                )

            logger.info(
                "Generated contribution: %s (%d files changed)",
                contribution.title,
                contribution.total_files_changed,
            )
            return contribution

        except Exception as e:
            logger.error("Failed to generate contribution for %s: %s", finding.title, e)
            return None

    async def _get_repo_preferences(self, context: RepoContext) -> dict | None:
        """Query memory for learned repo preferences.

        Returns dict with preferred_types, rejected_types, merge_rate
        or None if no memory or no data for this repo.
        """
        if not self._memory:
            return None
        try:
            return await self._memory.get_repo_preferences(context.repo.full_name)
        except Exception as e:
            logger.debug("Could not fetch repo preferences: %s", e)
            return None

    async def fix_contribution_from_error(
        self,
        contribution: Contribution,
        context: RepoContext,
        error_log: str,
    ) -> Contribution | None:
        """Self-correct a broken patch using the CI/test error log.

        Called by the pipeline when DockerSandbox reports test/compile failures.
        Prompts the LLM to analyze the error and produce a corrected patch.

        Args:
            contribution: The failed contribution (with original finding).
            context: RepoContext with file contents and repo metadata.
            error_log: The sandbox stdout/stderr from the failed test run.

        Returns:
            A new Contribution with a corrected patch, or None on failure.

        Raises:
            GenerationError: If the LLM output contains an AI disclosure
                or the corrected patch is still invalid.
        """
        logger.info(
            "🔧 Self-Correcting patch for '%s' using error log (%.200s)",
            contribution.title,
            error_log[:200],
        )

        # Build a focused prompt for the LLM
        error_context = (
            f"The following CI/test run FAILED with this output:\n\n"
            f"=== ERROR LOG ===\n{error_log}\n"
            f"=== END ERROR LOG ===\n\n"
            f"Your previous patch was incorrect. Please analyze the error above "
            f"and produce a corrected patch for the same finding.\n"
            f"Finding: {contribution.finding.description}\n"
            f"File: {contribution.changes[0].path if contribution.changes else 'unknown'}\n"
        )

        system = self._build_system_prompt(context)
        prompt = (
            f"{error_context}\n\n"
            f"--- Repository Context (do NOT make changes outside the relevant files) ---\n"
            f"Relevant files:\n"
            + "\n".join(
                f"File: {fp}\nContent:\n{content[:3000]}"
                for fp, content in context.relevant_files.items()
            )
        )

        # Ask LLM for corrected patch
        raw = await self._llm.complete(prompt, system=system, temperature=0.2)
        text = (raw or "").strip()

        # Gag Order check on raw LLM output (before parsing)
        if _GHOST_DISCLOSURE_RE.search(text):
            raise GenerationError(
                "Gag Order: LLM output in fix_contribution_from_error "
                "contains AI disclosure — aborting self-correction."
            )

        # Parse the corrected changes
        import json as _json
        try:
            parsed = _json.loads(text)
        except _json.JSONDecodeError:
            # Try to extract JSON from markdown fences
            import re as _re
            stripped = _re.sub(r"```(?:json)?\s*", "", text, flags=_re.IGNORECASE)
            stripped = _re.sub(r"```\s*$", "", stripped)
            try:
                parsed = _json.loads(stripped)
            except _json.JSONDecodeError as je:
                raise GenerationError(
                    f"fix_contribution_from_error: could not parse LLM response as JSON: {je}"
                ) from je

        # ── Inline Gag Order on parsed changes ─────────────────────────────
        _gag_check_fields = ["new_content", "original_content"]
        for item in parsed.get("changes", []):
            for field in _gag_check_fields:
                val = item.get(field, "") or ""
                if _GHOST_DISCLOSURE_RE.search(val):
                    raise GenerationError(
                        f"Gag Order: corrected patch contains AI disclosure in '{field}' — aborting."
                    )
        # ─────────────────────────────────────────────────────────────────

        # Parse changes inline (same logic as _parse_changes but self-contained)
        from farm_agent.core.models import FileChange
        corrected_changes: list[FileChange] = []
        for item in parsed.get("changes", []):
            path = str(item.get("path", "")).strip().strip("`\"'")
            is_new = item.get("is_new_file", False)

            if is_new:
                continue  # skip new files in self-correction

            if "edits" not in item:
                continue

            for edit_block in item["edits"]:
                search = edit_block.get("search", "") or ""
                replace = edit_block.get("replace", "") or ""
                if search == replace:
                    raise GenerationError(
                        f"fix_contribution_from_error: corrected patch is a no-op "
                        f"(search == replace) — aborting."
                    )

            fc = FileChange(
                path=path,
                original_content=context.relevant_files.get(path, ""),
                new_content=item.get("new_content", ""),
            )
            corrected_changes.append(fc)

        contribution.changes = corrected_changes
        logger.info(
            "✅ Self-Correction succeeded for '%s' — %d file(s) corrected",
            contribution.title,
            len(corrected_changes),
        )
        return contribution

    def _build_system_prompt(
        self,
        context: RepoContext,
        *,
        style_guide: str = "",
        project_map: str = "",
    ) -> str:
        """Build system prompt with repository context, style, and project map."""
        return build_generator_system_prompt(
            context,
            style_guide=style_guide,
            project_map=project_map,
            max_tokens=4000,
        )

    async def _agentic_generate(
        self,
        prompt: str,
        *,
        system: str,
        github_client=None,
        context: RepoContext | None = None,
    ) -> str:
        """Run the agentic generation loop with tool-calling support.

        If ``github_client`` is provided, the LLM can request file
        reads via the ``read_file`` tool.  The loop runs at most
        ``MAX_TOOL_CALLS`` tool invocations before forcing the LLM
        to generate the final code with whatever context it has.

        Falls back to a single ``self._llm.complete()`` call when
        no github_client is available (no tools).
        """
        if github_client is None:
            return await self._llm.complete(
                prompt, system=system, temperature=0.2,
            )

        # Build tool executor
        owner = context.repo.owner if context else ""
        repo_name = context.repo.name if context else ""
        tool = GitHubTool(github_client, owner=owner, repo=repo_name)

        # Prepare message history for the agentic loop
        messages: list[dict] = [
            {"role": "user", "content": prompt},
        ]
        tools = [READ_FILE_TOOL_SCHEMA]

        tool_calls_made = 0

        for _iteration in range(MAX_TOOL_CALLS + 1):
            response = await self._llm.complete_with_tools(
                messages,
                tools=tools if tool_calls_made < MAX_TOOL_CALLS else None,
                system=system,
                temperature=0.2,
            )

            # ── Text response → done ────────────────────────────────
            if not response.has_tool_calls:
                return response.text or ""

            # ── Tool call(s) → execute and loop ─────────────────────
            for tc in response.tool_calls:
                if tc.tool_name != "read_file":
                    logger.warning(
                        "Ignoring unknown tool call: %s", tc.tool_name,
                    )
                    continue

                filepath = tc.arguments.get("filepath", "")
                logger.info(
                    "🔧 Tool call: read_file('%s') [%d/%d]",
                    filepath, tool_calls_made + 1, MAX_TOOL_CALLS,
                )

                result = await tool.read_file(filepath)
                tool_calls_made += 1
                if result.success and filepath:
                    context.relevant_files[filepath] = str(result.data)

                # Append assistant's tool-call decision
                messages.append({
                    "role": "assistant",
                    "content": None,
                    "tool_calls": [{
                        "id": f"call_{tool_calls_made}",
                        "type": "function",
                        "function": {
                            "name": "read_file",
                            "arguments": json.dumps(tc.arguments),
                        },
                    }],
                })

                # Append tool result
                content = result.data if result.success else result.error
                messages.append({
                    "role": "tool",
                    "tool_call_id": f"call_{tool_calls_made}",
                    "content": str(content),
                })

            # If we've hit the tool call limit, stop offering tools
            if tool_calls_made >= MAX_TOOL_CALLS:
                logger.info(
                    "Tool call limit reached (%d). Forcing final generation.",
                    MAX_TOOL_CALLS,
                )

        # Shouldn't reach here, but safety fallback
        return await self._llm.complete(
            prompt, system=system, temperature=0.2,
        )

    def _build_generation_prompt(
        self, finding: Finding, context: RepoContext, *, repo_prefs: dict | None = None,
        adversarial_critique: str | None = None,
    ) -> str:
        """Build the generation prompt based on finding type."""
        # Get the current file content if available
        current_content = context.relevant_files.get(finding.file_path, "")

        type_instructions = {
            ContributionType.SECURITY_FIX: (
                "Fix this SECURITY vulnerability. Ensure the fix is complete "
                "and doesn't introduce new vulnerabilities."
            ),
            ContributionType.CODE_QUALITY: (
                "Improve the CODE QUALITY. Make the code cleaner, more maintainable, "
                "and more robust. Keep changes minimal and focused."
            ),
            ContributionType.README_FIX: (
                "Improve the DOCUMENTATION. Add missing docstrings, improve README sections, "
                "or fix documentation issues. Be thorough but concise."
            ),
            ContributionType.UI_UX_FIX: (
                "Fix this UI/UX issue. Improve accessibility, user experience, or visual design. "
                "Follow WCAG guidelines where applicable."
            ),
            ContributionType.PERFORMANCE_OPT: (
                "Optimize PERFORMANCE. Reduce time/space complexity, "
                "eliminate wasteful operations, or improve resource usage."
            ),
            ContributionType.FEATURE_ADD: (
                "Add this FEATURE. Keep the implementation clean, well-structured, and consistent "
                "with the existing codebase patterns."
            ),
            ContributionType.REFACTOR: (
                "REFACTOR this code. Improve structure and readability without changing behavior."
            ),
        }

        instruction = type_instructions.get(finding.type, "Fix this issue.")

        prompt = (
            f"## Task\n{instruction}\n\n"
            f"## Finding\n"
            f"- **Title**: {finding.title}\n"
            f"- **Severity**: {finding.severity.value}\n"
            f"- **File**: {finding.file_path}\n"
            f"- **Description**: {finding.description}\n"
        )

        # Inject repo preferences from outcome learning
        if repo_prefs:
            prefs_section = "\n## Repo Preferences (learned from past PRs)\n"
            if repo_prefs.get("rejected_types"):
                prefs_section += (
                    f"- **Avoid these PR types** (historically rejected): "
                    f"{', '.join(repo_prefs['rejected_types'])}\n"
                )
            if repo_prefs.get("preferred_types"):
                prefs_section += (
                    f"- **Preferred PR types** (historically merged): "
                    f"{', '.join(repo_prefs['preferred_types'])}\n"
                )
            if repo_prefs.get("merge_rate") is not None:
                rate = repo_prefs["merge_rate"]
                prefs_section += f"- **Merge rate**: {rate:.0%}\n"
            prompt += prefs_section

        if finding.suggestion:
            prompt += f"- **Suggestion**: {finding.suggestion}\n"

        if current_content:
            prompt += (
                f"\n## Current File Content ({finding.file_path})\n"
                f"```\n{current_content[:6000]}\n```\n"
            )

        # Cross-file: find other files with the same pattern
        other_affected_files = self._find_cross_file_instances(finding, context)
        if other_affected_files:
            prompt += (
                f"\n## ⚠️ IMPORTANT: Same issue in "
                f"{len(other_affected_files)} OTHER file(s)\n"
                "Fix ALL instances across ALL files in a single contribution.\n"
                "This produces a higher-quality PR that addresses the issue comprehensively.\n\n"
            )
            for fpath, fcontent in other_affected_files.items():
                # Sanitize RAG-retrieved content before injection to prevent
                # poisoned context from tricking the LLM into AI disclosures
                safe_path = _STRIP_AI_RE.sub("[sanitized]", fpath)
                safe_content = _STRIP_AI_RE.sub("[AI-disclosure redacted]", fcontent[:3000])
                if safe_path != fpath or safe_content != fcontent[:3000]:
                    logger.warning(
                        "RAG content sanitized — AI disclosure pattern removed from %s",
                        fpath,
                    )
                prompt += f"### {safe_path}\n```\n{safe_content}\n```\n\n"

        # Adversarial critique injection — append to rewrite prompts
        if adversarial_critique:
            prompt += (
                f"\n\n"
                f"## 🔴 ADVERSARIAL REVIEWER CRITIQUE (Must Fix Before Submitting)\n\n"
                f"The Senior Security Auditor REJECTED your previous patch with this feedback:\n\n"
                f"> {adversarial_critique}\n\n"
                f"Fix ALL issues raised above. Rewrite the patch to address each point exactly.\n"
                f"Do NOT repeat the same mistakes. Be thorough and precise.\n\n"
            )

        prompt += (
            "\n## Output Format\n"
            "Return ONLY a JSON object matching the requested schema.\n"
            "Do NOT include explanations, markdown fences, or <think> tags.\n\n"
        )

        if current_content:
            # For EXISTING files: use search/replace blocks to preserve content
            prompt += (
                "Since this is an EXISTING file, use SEARCH/REPLACE blocks "
                "to make targeted edits. DO NOT rewrite the entire file.\n\n"
                "```json\n"
                "{\n"
                '  "changes": [\n'
                "    {\n"
                '      "path": "path/to/file",\n'
                '      "is_new_file": false,\n'
                '      "edits": [\n'
                "        {\n"
                '          "search": "exact text to find in the file",\n'
                '          "replace": "replacement text"\n'
                "        }\n"
                "      ]\n"
                "    }\n"
                "  ]\n"
                "}\n"
                "```\n\n"
                "RULES for search/replace:\n"
                "- `search` must be an EXACT substring from the current file\n"
                "- `replace` is what replaces it (can be longer/shorter)\n"
                "- To ADD new content, search for the text BEFORE the insertion "
                "point and include it + the new content in `replace`\n"
                "- To DELETE content, set `replace` to empty string\n"
                "- Keep each edit small and focused\n"
                "- DO NOT include the entire file in search or replace\n\n"
                "⚠️ CRITICAL RULES — FAILURE TO FOLLOW THESE WILL BREAK THE PATCH ENGINE:\n"
                "1. The `search` value MUST be an EXACT, VERBATIM, copy-paste of a "
                "CONTINUOUS block of lines from the file above. Character-for-character.\n"
                "2. NEVER use `...` or `# ...` or any placeholder to skip lines. "
                "If your edit spans a large block, you MUST include EVERY SINGLE LINE "
                "between the first and last line of the search block.\n"
                "3. DO NOT modify indentation, whitespace, quotes, or any character "
                "in the `search` string. It must match the source file byte-for-byte.\n"
                "4. Each `search` block must contain enough surrounding context "
                "(at least 3-5 lines) to be UNIQUE within the file. Do not use "
                "a 1-line search that could match multiple locations.\n"
                "5. NEVER paraphrase, reformat, or re-indent code in the `search` block. "
                "Copy it EXACTLY as it appears in the file content provided above.\n"
            )
        else:
            # For NEW files: provide full content
            prompt += (
                "Since this is a NEW file, provide the full content:\n\n"
                "```json\n"
                "{\n"
                '  "changes": [\n'
                "    {\n"
                '      "path": "path/to/file",\n'
                '      "content": "full content of the new file",\n'
                '      "is_new_file": true\n'
                "    }\n"
                "  ]\n"
                "}\n"
                "```\n"
            )

        return prompt

    def _find_cross_file_instances(self, finding: Finding, context: RepoContext) -> dict[str, str]:
        """Find other files in the repo with the same issue pattern (X-Ray Vision via RAG).

        Uses ChromaDB semantic search to find code chunks related to the finding.
        Falls back to the old regex approach if ChromaDB is unavailable.
        """
        if not finding.file_path or not context.relevant_files:
            return {}

        # Build a semantic query from the finding
        query_parts = [finding.title]
        if finding.description:
            query_parts.append(finding.description[:200])
        if finding.suggestion:
            query_parts.append(finding.suggestion[:200])
        query_text = " ".join(query_parts)

        indexer = RepoIndexer()

        try:
            # Index all relevant files for semantic search
            chunk_count = indexer.index_repo(context.repo.full_name, context.relevant_files)
            if chunk_count == 0:
                return {}

            # Query for semantically related code chunks
            results = indexer.query_context(query_text, n_results=8)

            if not results:
                logger.warning(
                    "RAG query returned empty for '%s'. Falling back to regex extraction.",
                    finding.title,
                )
                return {}

            # Group by file and deduplicate
            other_files: dict[str, str] = {}
            seen_files: set[str] = set()
            for r in results:
                fpath = r["file_path"]
                if fpath == finding.file_path or fpath in seen_files:
                    continue
                if len(other_files) >= 3:
                    break
                other_files[fpath] = r["content"]
                seen_files.add(fpath)

            if other_files:
                logger.info(
                    "🔗 [RAG X-Ray] Found related context in %d other file(s): %s",
                    len(other_files),
                    ", ".join(other_files.keys()),
                )
            return other_files

        except Exception as exc:
            logger.warning(
                "RAG cross-file search failed for '%s', falling back to regex: %s",
                finding.title,
                exc,
            )
            # Fallback to old regex-based approach
            keywords = self._extract_search_patterns(finding)
            if not keywords:
                return {}

            other_files: dict[str, str] = {}
            for fpath, content in context.relevant_files.items():
                if fpath == finding.file_path:
                    continue
                content_lower = content.lower()
                matches = sum(1 for kw in keywords if kw.lower() in content_lower)
                if matches >= 2:
                    other_files[fpath] = content
                    if len(other_files) >= 3:
                        break

            if other_files:
                logger.info(
                    "🔗 [RAG fallback] Found same pattern in %d other file(s): %s",
                    len(other_files),
                    ", ".join(other_files.keys()),
                )
            return other_files
        finally:
            indexer.destroy()

    @staticmethod
    def _extract_search_patterns(finding: Finding) -> list[str]:
        """Extract code patterns from finding description to search across files.

        Looks for code-like tokens in the finding's description and suggestion.
        """
        patterns = []
        text = f"{finding.description} {finding.suggestion or ''}"
        # Extract backtick-quoted code snippets
        import re

        for match in re.findall(r"`([^`]+)`", text):
            if len(match) > 3:  # Skip very short matches
                patterns.append(match)
        # Extract common code patterns mentioned
        for pattern in re.findall(r"(\w+\.\w+[!?]?(?:\(\))?)", text):
            if len(pattern) > 5:
                patterns.append(pattern)
        return patterns[:10]  # Cap at 10 patterns

    def _parse_changes(self, response: str, context: RepoContext) -> list[FileChange]:
        """Parse LLM response into FileChange objects.

        Supports two formats:
        1. Search/replace blocks (for existing files) — applies edits to original
        2. Full content (for new files) — uses content as-is
        """
        import yaml

        changes: list[FileChange] = []

        try:
            cleaned_response = re.sub(
                r"<think>[\s\S]*?</think>",
                "",
                response,
                flags=re.IGNORECASE,
            ).strip()

            payload_text = None

            json_match = re.search(
                r"```json\s*\n(.*?)\n\s*```",
                cleaned_response,
                re.DOTALL | re.IGNORECASE,
            )
            if json_match:
                payload_text = json_match.group(1)
            else:
                json_match = re.search(
                    r"\{[\s\S]*?(?:\"changes\"|'changes')[\s\S]*\}",
                    cleaned_response,
                )
                if json_match:
                    payload_text = json_match.group(0)
                else:
                    yaml_match = re.search(
                        r"changes:\s*[\s\S]*",
                        cleaned_response,
                        re.IGNORECASE,
                    )
                    if yaml_match:
                        payload_text = yaml_match.group(0)

            if not payload_text:
                return []

            try:
                data = json.loads(payload_text)
            except json.JSONDecodeError:
                data = yaml.safe_load(payload_text)

            if isinstance(data, dict):
                raw_changes = data.get("changes", [])
            elif isinstance(data, list):
                raw_changes = data
            else:
                return []

            for item in raw_changes:
                if not isinstance(item, dict) or "path" not in item:
                    continue

                path = str(item["path"]).strip().strip("`\"'")
                is_new = item.get("is_new_file", False)

                # ── Discipline Protocol: Block scratchpad/note files ────────────
                if is_new:
                    _SCRATCHPAD_PATTERNS = (
                        "note", "explore", "exploration", "scratchpad",
                        "temp_", "tmp_", "draft", "wip_", "thought",
                    )
                    path_lower = path.lower()
                    is_scratchpad = any(p in path_lower for p in _SCRATCHPAD_PATTERNS)
                    # Block .md/.txt placed in src/ or source/ directories
                    is_md_in_src = (
                        path_lower.startswith(("src/", "source/", "app/", "lib/"))
                        and path_lower.endswith((".md", ".txt"))
                    )
                    if is_scratchpad or is_md_in_src:
                        logger.warning(
                            "🗑️ Discipline Protocol: rejecting new file '%s' "
                            "(scratchpad=%s, md_in_src=%s) — "
                            "non-code or note file in source dir is forbidden.",
                            path, is_scratchpad, is_md_in_src,
                        )
                        raise GenerationError(
                            f"Generator produced a forbidden scratchpad/note file: {path}"
                        )
                # ─────────────────────────────────────────────────────────────────

                if "edits" in item and not is_new:
                    # Search/replace mode — apply edits to original content
                    original = context.relevant_files.get(path, "")
                    if not original:
                        logger.warning(
                            "No original content for %s (finding file not fetched), skipping edits",
                            path,
                        )
                        continue

                    new_content = original
                    edits_applied = 0
                    edits_total = len(item["edits"])
                    for edit in item["edits"]:
                        search = edit.get("search", "")
                        replace = edit.get("replace", "")
                        if not search:
                            continue

                        matched = False

                        # Try 1: Exact match
                        if search in new_content:
                            new_content = new_content.replace(search, replace, 1)
                            matched = True

                        # Try 2: Normalize trailing whitespace per line
                        if not matched:
                            norm_search = "\n".join(line.rstrip() for line in search.split("\n"))
                            norm_content = "\n".join(
                                line.rstrip() for line in new_content.split("\n")
                            )
                            if norm_search in norm_content:
                                idx = norm_content.index(norm_search)
                                start_line = norm_content[:idx].count("\n")
                                end_line = start_line + norm_search.count("\n")
                                lines = new_content.split("\n")
                                lines[start_line : end_line + 1] = replace.split("\n")
                                new_content = "\n".join(lines)
                                matched = True
                                logger.debug(
                                    "Fuzzy match (whitespace normalized) for %s",
                                    path,
                                )

                        # Try 3: Strip all leading/trailing whitespace
                        if not matched:
                            stripped_search = search.strip()
                            if len(stripped_search) > 20 and stripped_search in new_content:
                                new_content = new_content.replace(
                                    stripped_search, replace.strip(), 1
                                )
                                matched = True
                                logger.debug(
                                    "Fuzzy match (stripped) for %s",
                                    path,
                                )

                        # Try 4: Indentation-agnostic line-by-line matching
                        # Strips leading whitespace from each line for
                        # comparison, then re-applies the original file's
                        # indentation to the replacement block.
                        if not matched:
                            search_lines = search.split("\n")
                            content_lines = new_content.split("\n")
                            stripped_search_lines = [l.lstrip() for l in search_lines]

                            # Slide a window of len(search_lines) over content
                            window = len(search_lines)
                            if window >= 2:  # Require at least 2 lines for safety
                                for start_idx in range(len(content_lines) - window + 1):
                                    candidate = content_lines[start_idx : start_idx + window]
                                    candidate_stripped = [l.lstrip() for l in candidate]
                                    if candidate_stripped == stripped_search_lines:
                                        # Match found — re-indent replacement
                                        # using the original file's leading whitespace
                                        replace_lines = replace.split("\n")
                                        reindented: list[str] = []
                                        for j, rline in enumerate(replace_lines):
                                            if j < len(candidate):
                                                # Borrow indent from the corresponding original line
                                                orig_indent = candidate[j][: len(candidate[j]) - len(candidate[j].lstrip())]
                                            elif candidate:
                                                # Extra lines: use indent of the last matched line
                                                last = candidate[-1]
                                                orig_indent = last[: len(last) - len(last.lstrip())]
                                            else:
                                                orig_indent = ""
                                            # Strip the LLM's indent and apply the file's indent
                                            reindented.append(orig_indent + rline.lstrip())

                                        content_lines[start_idx : start_idx + window] = reindented
                                        new_content = "\n".join(content_lines)
                                        matched = True
                                        logger.debug(
                                            "Indent-agnostic match for %s (lines %d-%d)",
                                            path, start_idx + 1, start_idx + window,
                                        )
                                        break

                        if matched:
                            # Diff Minimizer: reject edits where the LLM
                            # rewrote far more than it searched for — a sign
                            # of hallucinated full-function rewrites.
                            search_line_count = len(search.split("\n"))
                            replace_line_count = len(replace.split("\n"))
                            MAX_REPLACE_TO_SEARCH_RATIO = 2
                            if search_line_count > 0 and (replace_line_count / search_line_count) > MAX_REPLACE_TO_SEARCH_RATIO:
                                logger.warning(
                                    "Diff Minimizer blocked: replace/search ratio %.1f exceeds limit %d in %s",
                                    replace_line_count / search_line_count,
                                    MAX_REPLACE_TO_SEARCH_RATIO,
                                    path,
                                )
                                continue
                            if replace_line_count > 50:
                                logger.warning(
                                    "Diff Minimizer blocked: replace block too large "
                                    "(%d lines) in %s",
                                    replace_line_count,
                                    path,
                                )
                                continue
                            edits_applied += 1
                        else:
                            logger.warning(
                                "Search text not found in %s (tried exact + fuzzy + indent-agnostic). "
                                "Search[:%d]: %.80s...",
                                path,
                                len(search),
                                search.replace("\n", "\\n"),
                            )


                    logger.info(
                        "Edits for %s: %d/%d applied",
                        path,
                        edits_applied,
                        edits_total,
                    )

                    if edits_applied == 0:
                        logger.warning("No edits applied to %s, skipping file", path)
                        continue

                    changes.append(
                        FileChange(
                            path=path,
                            original_content=original,
                            new_content=new_content,
                            is_new_file=False,
                        )
                    )

                elif "content" in item:
                    # Full content mode (new files or fallback)
                    changes.append(
                        FileChange(
                            path=path,
                            new_content=item["content"],
                            is_new_file=is_new,
                        )
                    )

        except (json.JSONDecodeError, KeyError, TypeError) as e:
            logger.warning("Failed to parse changes JSON: %s", e)

        # Enforce max files limit
        if len(changes) > self._config.max_files_per_pr:
            logger.warning(
                "Too many files changed (%d > %d), truncating",
                len(changes),
                self._config.max_files_per_pr,
            )
            changes = changes[: self._config.max_files_per_pr]

        # ── Gag Order — Regex sanitizer against AI disclosures ───────────────
        for change in changes:
            for attr in ("new_content", "original_content"):
                val = getattr(change, attr, "") or ""
                if _GHOST_DISCLOSURE_RE.search(val):
                    logger.warning(
                        "🗑️ Gag Order triggered — AI disclosure detected in %s. "
                        "Aborting contribution for file %s.",
                        attr, change.path,
                    )
                    raise GenerationError(
                        f"L LM output contains forbidden AI disclosure: {change.path}"
                    )
        # ─────────────────────────────────────────────────────────────────────

        return changes

    async def _generate_commit_message(
        self, finding: Finding, changes: list[FileChange], context: RepoContext
    ) -> str:
        """Generate a conventional commit message."""
        type_prefixes = {
            ContributionType.SECURITY_FIX: "fix(security)",
            ContributionType.CODE_QUALITY: "refactor",
            ContributionType.README_FIX: "docs",
            ContributionType.UI_UX_FIX: "fix(ui)",
            ContributionType.PERFORMANCE_OPT: "perf",
            ContributionType.FEATURE_ADD: "feat",
            ContributionType.REFACTOR: "refactor",
        }

        prefix = type_prefixes.get(finding.type, "fix")
        files = ", ".join(c.path.split("/")[-1] for c in changes[:3])

        if self._config.commit_convention == "conventional":
            # Try to extract scope from file path
            scope = ""
            if changes:
                parts = changes[0].path.split("/")
                if (len(parts) >= 2 and parts[0] in ("packages", "apps", "libs")) or (
                    len(parts) >= 2 and parts[0] == "src"
                ):
                    scope = parts[1]
            if scope:
                msg = (
                    f"{prefix}({scope}): {finding.title.lower()}\n\n"
                    f"{finding.description}\n\n"
                    f"Affected files: {files}"
                )
            else:
                msg = (
                    f"{prefix}: {finding.title.lower()}\n\n"
                    f"{finding.description}\n\n"
                    f"Affected files: {files}"
                )
        elif self._config.commit_convention == "angular":
            scope = changes[0].path.split("/")[0] if changes else ""
            msg = f"{prefix}({scope}): {finding.title.lower()}"
        else:
            msg = finding.title
        # ── Gag Order — sanitize commit message before use ──
        return _sanitize_text(msg, "commit message")

    def _generate_branch_name(self, finding: Finding) -> str:
        """Generate a clean branch name from finding."""
        prefix_map = {
            ContributionType.SECURITY_FIX: "fix/security",
            ContributionType.CODE_QUALITY: "improve/quality",
            ContributionType.README_FIX: "docs",
            ContributionType.UI_UX_FIX: "fix/ui",
            ContributionType.PERFORMANCE_OPT: "perf",
            ContributionType.FEATURE_ADD: "feat",
            ContributionType.REFACTOR: "refactor",
        }
        prefix = prefix_map.get(finding.type, "fix")
        # Clean title for branch name
        slug = re.sub(r"[^a-zA-Z0-9]+", "-", finding.title.lower()).strip("-")[:40]
        return f"{prefix}/{slug}"

    def _generate_pr_title(self, finding: Finding, *, guidelines=None) -> str:
        """Generate a PR title adapted to repo conventions."""
        # Use adaptive title if guidelines available
        if guidelines and guidelines.has_guidelines:
            from farm_agent.github.guidelines import (
                adapt_pr_title,
                extract_scope_from_path,
            )

            scope = extract_scope_from_path(finding.file_path or "", guidelines)
            return adapt_pr_title(
                finding.title,
                finding.type.value,
                guidelines,
                scope=scope,
            )

        # Default: emoji format
        type_labels = {
            ContributionType.SECURITY_FIX: "🔒 Security",
            ContributionType.CODE_QUALITY: "✨ Quality",
            ContributionType.README_FIX: "📝 Docs",
            ContributionType.UI_UX_FIX: "🎨 UI/UX",
            ContributionType.PERFORMANCE_OPT: "⚡ Performance",
            ContributionType.FEATURE_ADD: "🚀 Feature",
            ContributionType.REFACTOR: "♻️ Refactor",
        }
        label = type_labels.get(finding.type, "🔧 Fix")
        return f"{label}: {finding.title}"

    async def _self_review(self, contribution: Contribution, context: RepoContext) -> bool:
        """Have the LLM self-review the generated contribution."""
        changes_summary = "\n".join(
            f"- {c.path} ({'new' if c.is_new_file else 'modified'})" for c in contribution.changes
        )

        prompt = (
            "Review the following code contribution for quality:\n\n"
            f"**Title**: {contribution.title}\n"
            f"**Type**: {contribution.contribution_type.value}\n"
            f"**Finding**: {contribution.finding.description}\n"
            f"**Changes**:\n{changes_summary}\n\n"
            "For each changed file:\n"
        )
        for change in contribution.changes[:5]:
            review_snippet = self._build_review_snippet(change)
            prompt += f"\n### {change.path}\n```diff\n{review_snippet}\n```\n"

        prompt += (
            "\nAnswer these questions:\n"
            "1. Does the change correctly fix the described issue?\n"
            "2. Does it introduce any new bugs or security issues?\n"
            "3. Does it follow good coding practices?\n"
            "4. Is the change minimal and focused?\n\n"
            "Reply with APPROVE or REJECT followed by brief reasoning."
        )

        try:
            response = await self._llm.complete(prompt, temperature=0.1)
            response_upper = response.upper()
            if "REJECT" in response_upper:
                logger.info("Self-review rejected: %s", response[:200])
                return False
            if "APPROVE" in response_upper:
                return True
            logger.warning(
                "Self-review returned unrecognized verdict, approving by default: %s",
                response[:200],
            )
            return True
        except Exception as e:
            logger.warning("Self-review failed, approving by default: %s", e)
            return True  # Don't block on review failures

    @staticmethod
    def _build_review_snippet(change: FileChange, max_chars: int = 2000) -> str:
        """Build a compact diff-oriented review snippet for self-review."""
        if change.original_content is not None:
            diff = "".join(
                difflib.unified_diff(
                    change.original_content.splitlines(keepends=True),
                    change.new_content.splitlines(keepends=True),
                    fromfile=f"a/{change.path}",
                    tofile=f"b/{change.path}",
                    n=3,
                )
            ).strip()
            if diff:
                return diff[:max_chars]

        return change.new_content[:max_chars]
